### ISSUE TITLE
Recommended usage?

### ISSUE THREAD

**Issue by dscottboggs** [ysbaddaden/posix#7]
I've added this project as a dependency and added a postinstall hook to run make, then tried to require "posix/../target/.../unistd" and got this error

```
Showing last frame. Use --error-trace for full trace.

In lib/posix/targets/x86_64-linux-gnu/c/stddef.cr:6:3

 6 | alias SizeT = ULong
     ^
Error: alias SizeT is already defined
```

Am I doing this wrong?

Edit: in case it's not obvious, the reason `LibC::SizeT` is already defined is because it's part of the stdlib. Do I need to compile a Crystal compiler with this library somehow inserted?

**Comment by ysbaddaden** [comment]
This repository is an application, not a shard. It's meant to generate complete POSIX bindings for whatever targets.

It will conflict with corelib bindings, unless you put the generated bindings in a place where Crystal will load them _instead of_ the corelib ones, like `lib/c/x86_64-linux-gnu` for example, or something like that.

That being said, it wasn't updated in 4 years and uses libclang 3.9, which is very outdated.
